const dataSlider = {
  imgs: [
    {
      id: 0,
      smallvalue: "/images/banner/mini1.jpg",
      value: "/images/banner/1.jpg",
      title: "",
      description: "",
      detail: "",
      altIamgeText: "Sldier Name 1",
      button: "",
      link: "",
      lintAlt: "",
    },
    {
      id: 1,
      smallvalue: "/images/banner/mini1.jpg",
      value: "/images/banner/2.jpg",
      title: "",
      description: "",
      detail: "",
      altIamgeText: "Sldier Name 2",
      button: "",
      link: "",
      lintAlt: "",
    },
    {
      id: 2,
      smallvalue: "/images/banner/mini1.jpg",
      value: "/images/banner/3.jpg",
      title: "",
      description: "",
      detail: "",
      altIamgeText: "Sldier Name 3",
      button: "",
      link: "",
      lintAlt: "",
    },
    {
      id: 3,
      smallvalue: "/images/banner/mini1.jpg",
      value: "/images/banner/4.jpg",
      title: "",
      description: "",
      detail: "",
      altIamgeText: "Sldier Name 4",
      button: "",
      link: "",
      lintAlt: "",
    },
  ],
};

export default dataSlider;
